services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-awtik_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: web
    # Сначала применяем миграции, затем запускаем сервер
    command: sh -c "alembic upgrade head && gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 main:app"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: